// e=propmt("enter the no.")
// o=e%2
// switch(o){
// case 0:
//     document.write("the value is even")
// break;
// case 1:
//     document.write("the value is odd")
// break;
// default:
// document.write("write valid no.")

// }
// document.write("hello")
// weekdays=parseInt(prompt("enter the no."))
// switch(weekdays){
// case 1:
//     document.write("Monday")
//     break;
// case 2:
//     document.write("Tuesday")
//     break;
// case 3:
//     document.write("Wednesday")
//     break;
// case 4:
//     document.write("Thursday")
//     break;
// case 5:
//     document.write("Friday")
//     break;
//     case 6:
//         document.write("Saturday")
//         break;
//         case 7:
//             document.write("Sunday")
//             break;
//             default:
//                 document.write("enter according to weekdays no."s)









// }

// fruits=prompt("enter your favourite fruit")
// switch(fruits){
// case "strawberry" :
// document.write("red")
// break;
// case "kiwi":
//     document.write("green")
//     break;
//     case "papaya":
//         document.write("yellow")
//         break;
//         case "blackberry" :
//         document.write("black")
//         break;
//         case "orange" :
//         document.write("orange")
//         break;
//         default:
//             document.write("enter valid fruit name")

// }
// 

// 

// a=parseInt(prompt("enter your serving year"))
// b=parseInt(prompt("enter your salary"))
// c=b+b*5/100
// if(a>=5){
//

// }


// for(i=0;i<a.length;++i){
//     sum=sum+a[i]
// }
// document.write(sum)
// min=a[0]
// for(i=0;i<a.length;++i){
//     if(min>a[i]){
// min=a[i]
// }
// }
// document.write(min)
// max=0
// for(i=0;i<a.length;++i){
//     if(max<a[i]){
//         max=a[i]
//     }
// }
// document.write(max)
// for(i=0;i<a.length;++i){
//     if(a[i]%2==0){
//         document.write(a[i],'is the even no. <br>')
//     }
// }
// a=[23,34,44,53,4,7]
// for(i=0;i<a.length;++i){
    
// }
// document.write(a.length)
// total=0
// for(i=0;i<a.length;++i){

// if(a[i]%2==0){
//     total=total+a[i]
// document.write(a[i],'is the even no. <br>')
// }
// }

// document.write(total)
// b=[43,23,7,64,23,67]

// for(i=0;i<a.length;++i){
// if(a[i]==b.length){
//     document.write(a[i],'<br>')  
// }
// }

// a=[87,54,37,73,12,34,54,11]
// ascending=0
// for(i=0;i<a.length;++i){

// //     ascending=ascending+a[i]
// }


// document.write(a.sort())

// for(i=0;i<a.length;++i){
// }














function cvv(){
    a = document.getElementById('c')
    
    if (a.style.display!='none')
    {
a.style.display='none'
document.body.style.background='orange'
    }

    
    else{
        a.style.display='block'
        a.style.background='green'
        
    }
}
    

